/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9017fb00-088a-4cda-b148-8f2aef03d3c6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rKIYoVF3v",
    "aws_user_pools_web_client_id": "24ee2vhkqtja6cj4e8sseuv0ds",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xyk57q2bqvey5n5cu2ktpmzzla.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x6cmkb4ahzgq3nl4zsijq22scy",
    "aws_cloud_logic_custom": [
        {
            "name": "helloworld",
            "endpoint": "https://d3bcca0usb.execute-api.us-east-1.amazonaws.com/angbackdev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
